### ISSUE TITLE
There is no all projects?

### ISSUE THREAD

**Issue by hakimov-dev** [anvaka/map-of-github-data#23]
Why there isn't every projects from github ?

**Comment by anvaka** [comment]
The recommendations are built based on stars given to projects. if there is not enough stars given I cannot make a meaningful project recommendation so I don't add the project to the map.

Additionally the stars processed are between Jan 2020 and Mar 2023, so if your project got popular after this period - it will not be shown yet

**Comment by hakimov-dev** [comment]
At least how much should i have star ?

**Comment by anvaka** [comment]
Around 300 stars would be a good bet

**Comment by hakimov-dev** [comment]
Ok, thank.

**Comment by flckv** [comment]
not even map-of-github-data is on the map. I guess without the 300 star filter - there would be a lot of duplicate repos - and would cost a lot to parse below 300 stars, right? Do you have an estimate how much it would cost to include low/no star repos that are unique?

**Comment by phanirithvij** [comment]
Also, are the indexing scripts available somewhere? I couldn't find them in this repo nor the main one.

I am specifically asking for the scripts which get the repositories from github and then generate these geojson files.
